Traceback (most recent call last):
  File "c:\Users\iacop\Desktop\Programmazione\Github\tum-adlr-11\2D_Shape_Completion\main1.py", line 151, in <module>
    main()
  File "c:\Users\iacop\Desktop\Programmazione\Github\tum-adlr-11\2D_Shape_Completion\main1.py", line 56, in main
    mean, std = calculate_mean_std(dataset)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\iacop\Desktop\Programmazione\Github\tum-adlr-11\2D_Shape_Completion\main1.py", line 28, in calculate_mean_std
    for inputs, _ in loader:
  File "C:\Users\iacop\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py", line 701, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\iacop\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py", line 1465, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iacop\anaconda3\Lib\site-packages\torch\utils\data\dataloader.py", line 1491, in _process_data
    data.reraise()
  File "C:\Users\iacop\anaconda3\Lib\site-packages\torch\_utils.py", line 715, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\iacop\anaconda3\Lib\site-packages\torch\utils\data\_utils\worker.py", line 351, in _worker_loop
    data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iacop\anaconda3\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iacop\anaconda3\Lib\site-packages\torch\utils\data\_utils\fetch.py", line 52, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "c:\Users\iacop\Desktop\Programmazione\Github\tum-adlr-11\2D_Shape_Completion\create_dataset_file.py", line 51, in __getitem__
    input_image = self.transform(input_image)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\iacop\anaconda3\Lib\site-packages\torchvision\transforms\transforms.py", line 137, in __call__
    return F.to_tensor(pic)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\iacop\anaconda3\Lib\site-packages\torchvision\transforms\functional.py", line 142, in to_tensor
    raise TypeError(f"pic should be PIL Image or ndarray. Got {type(pic)}")
TypeError: pic should be PIL Image or ndarray. Got <class 'torch.Tensor'>
